spring:
  datasource:
    url: jdbc:mysql://rm-wz9xv0y580bh2xxd2no.mysql.rds.aliyuncs.com:3306/tb_order?characterEncoding=utf-8
    username: view
    password: Cm123123
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka



